include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/**.dart
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    avoid_renaming_method_parameters: false