name: bid_right_mobile
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  collection:
  connectivity_plus: ^5.0.1
  dio: ^5.0.2
  dotted_border: ^2.1.0
  email_validator: ^2.0.1
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  extended_masked_text: ^2.3.1
  firebase_analytics: ^10.1.1
  firebase_core: ^2.7.0
  firebase_crashlytics: ^3.0.12
  firebase_messaging: ^14.2.5
  fixnum: ^1.0.0
  flutter_app_badger:
    git:
      url: https://github.com/g123k/flutter_app_badger.git # 1.5.0 doesn't support iOS 17
  flutter_bloc: ^8.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_google_places_hoc081098: ^1.0.1
  flutter_libphonenumber: ^1.2.2
  flutter_local_notifications: ^16.2.0
  flutter_map: ^6.1.0
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.3
  font_awesome_flutter: ^10.0.0
  freezed_annotation: ^2.4.1
  grpc:
    git:
      url: https://github.com/songfei/grpc-dart.git
      ref: 79a43b041d06d207f7e80e0e4d88fb6629338156
  intl: ^0.18.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  local_auth: ^2.0.0
  local_auth_android:
  package_info_plus: ^3.0.3
  plaid_flutter: ^3.1.0
  protobuf: ^2.1.0
  provider: ^6.0.0
  rxdart: ^0.27.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.8
  sliver_tools: ^0.2.11
  smooth_page_indicator: ^1.0.0
  step_progress_indicator: ^1.0.0
  url_launcher: ^6.0.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  dart_code_metrics: ^5.6.0
  dependency_validator: ^3.1.0
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

dependency_overrides:
  http: ^1.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          style: italic
          weight: 700